services:
  api:
    build: .
    container_name: "api-service"
    env_file: .env
    ports:
      - 3000:3000
    environment:
      - WDS_SOCKET_HOST= 127.0.0.1
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING= true
    volumes:
      - ./:/app
  db:
    image: mongo:8.0-rc-noble
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
